% Produced by CVXGEN, 2021-01-15 09:44:47 -0500.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
Fd = params.Fd;
Td = params.Td;
tau = params.tau;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable dotx_2(3, 1);

  minimize(quad_form(dotx_2, eye(3)));
  subject to
    tau*Fd'*dotx_2 >= -Td;
cvx_end
vars.dotx_2 = dotx_2;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
